# Trainer args for debugging model
# trainer api: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#trainer-class-api
_target_: pytorch_lightning.Trainer


# technical
gpus: 0
accelerator: 'ddp_cpu'
num_processes: 4
precision: 32

min_epochs: 1
max_epochs: 3

# prints
enable_model_summary: full
profiler: null

# all parameters below are set to Lightning defaults

# tricks
# gradient_clip_val: 0
# accumulate_grad_batches: 1
# val_check_interval: 1.0
# check_val_every_n_epoch: 1
# stochastic_weight_avg: False

# debug
# num_sanity_val_steps: 2
# fast_dev_run: False
# overfit_batches: 0
# limit_train_batches: 1.0
# limit_val_batches: 1.0
# limit_test_batches: 1.0
# track_grad_norm: -1
# terminate_on_nan: False
