# trainer api: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#trainer-class-api
_target_: pytorch_lightning.Trainer

# technical
gpus: -1
accelerator: 'ddp'
precision: 16

# training routine
min_epochs: 1
max_epochs: 50

# logging
log_every_n_steps: 10
weights_summary: top # information about the model
resume_from_checkpoint: null # Path to checkpoint to continue training (!surround with '' when calling via CLI!)
