# trainer api: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#trainer-class-api
_target_: pytorch_lightning.Trainer

# technical
accelerator: 'gpu'
devices: [0]
strategy: 'ddp_find_unused_parameters_false'
precision: 16

# training routine
min_epochs: 1
max_epochs: 5

# logging
log_every_n_steps: 10
enable_model_summary: full # information about the model
