name: unsupervised_learning

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pandas=1.2.4
  - numpy=1.19.2
  - pillow=7.2.0
  - tqdm=4.60.0
  - scikit-image=0.19.2
  - pip:
      - -r requirements.txt
