name: unsupervised_learning

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - cudatoolkit=10.2
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pip:
      - -r requirements.txt
