name: unsupervised_learning

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - cudatoolkit=10.2
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pandas=1.3.2
  - numpy=1.19.2
  - pillow=7.2.0
  - tqdm=4.60.0
  - pip:
      - -r requirements.txt
