run:
    dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
    dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

job:
    # you can set here environment variables that are universal for all users
    # for system specific variables (like data paths) it's better to use .env file!
    env_set:
        # currently there are some issues with running sweeps alongside wandb
        # https://github.com/wandb/client/issues/1314
        # this env var fixes that
        WANDB_START_METHOD: thread