_target_: pl_bolts.models.vision.UNet

num_classes: 8
num_layers: 2
features_start: 32

#path_to_weights: 'path/to/checkpoint' # path to the checkpoint(.pth) with surrounded with ''
#strict: False  # if you want to load the weights in a non-strict manner (https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict) (load_state_dict())
