_target_: src.models.backbones.unet.OldUNet
num_layers: 5
num_classes: 4
features_start: 64

input_channels: 3
bilinear: False

#path_to_weights: 'path/to/checkpoint' # path to the checkpoint(.pth) with surrounded with ''
#strict: False  # if you want to load the weights in a non-strict manner (https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict) (load_state_dict())
