_target_: src.models.semantic_segmentation.semantic_segmentation.SemanticSegmentation

model: null
#output_path: './output'  # looks like we dont need it (remove everywhere)
create_confusion_matrix: False
calc_his_miou_train_val: False
calc_his_miou_test: False