# CARE: this callbacks can cause semaphore leaks
# We are waiting for a pytorch lightning update which fixes this problem
# https://github.com/DIVA-DIA/unsupervised_learning/issues/61
save_f1_precision_recall_heatmap:
    _target_: src.callbacks.wandb_callbacks.LogF1PrecRecHeatmapToWandb