# documentation for precision: https://torchmetrics.readthedocs.io/en/latest/references/functional.html#precision-func
# for recall: https://torchmetrics.readthedocs.io/en/latest/references/functional.html#recall-func
# for f1: https://torchmetrics.readthedocs.io/en/latest/references/functional.html#f1-func
save_f1_precision_recall_heatmap:
    _target_: src.callbacks.wandb_callbacks.LogF1PrecRecHeatmapToWandb