defaults:
    - default_callbacks.yaml


watch_model:
    _target_: src.callbacks.wandb_callbacks.WatchModelWithWandb
    log: "all"
    log_freq: 100


upload_code:
    _target_: src.callbacks.wandb_callbacks.UploadCodeToWandbAsArtifact
    code_dir: ${work_dir}


upload_ckpts:
    _target_: src.callbacks.wandb_callbacks.UploadCheckpointsToWandbAsArtifact
    ckpt_dir: "checkpoints/"
    upload_best_only: True


save_f1_precision_recall_heatmap:
    _target_: src.callbacks.wandb_callbacks.LogF1PrecRecHeatmapToWandb


save_confusion_matrix:
    _target_: src.callbacks.wandb_callbacks.LogConfusionMatrixToWandb
