_target_: src.datamodules.hisDBDataModule.DIVAHisDBDataModule.DIVAHisDBDataModuleCropped


data_dir: /netscratch/datasets/semantic_segmentation/datasets_cropped/CB55-10-segmentation
crop_size: 256
num_workers: 4
batch_size: 16
shuffle: True
drop_last_batch: True