_target_: src.datamodules.DivaHisDB.datamodule_cropped.DivaHisDBDataModuleCropped

data_dir: /net/research-hisdoc/datasets/semantic_segmentation/datasets_cropped/CB55
crop_size: 256
num_workers: 4
batch_size: 16
shuffle: True
drop_last: True