_target_: src.datamodules.RolfFormat.datamodule.DataModuleRolfFormat

num_workers: 4
batch_size: 16
shuffle: True
drop_last: True

data_root: /netscratch/datasets/semantic_segmentation/rolf_format

train_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1000
        range_to:   1029
    append2:
        doc_dir:    "SetA1_sizeM_Rolf/layoutR/data"
        doc_names:  "A1-MR-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutR/gtruth"
        gt_names:   "A1-MR-truthD-####.gif"
        range_from: 1600
        range_to:   1609

val_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1000
        range_to:   1029
    append2:
        doc_dir:    "SetA1_sizeM_Rolf/layoutR/data"
        doc_names:  "A1-MR-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutR/gtruth"
        gt_names:   "A1-MR-truthD-####.gif"
        range_from: 1600
        range_to:   1609

test_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1800
        range_to:   1809
    append2:
        doc_dir:    "SetA1_sizeM_Rolf/layoutR/data"
        doc_names:  "A1-MR-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutR/gtruth"
        gt_names:   "A1-MR-truthD-####.gif"
        range_from: 1800
        range_to:   1809

image_analytics:
    mean:
        R: 0.8705590692084239
        G: 0.7458294488380534
        B: 0.6311273887799564
    std:
        R: 0.18879972204374673
        G: 0.18806443944992593
        B: 0.17460372273808386

image_dims:
    width:  640
    height: 896

classes:
    background:
        color:
            R:  0
            G:  0
            B:  0
        weight: 0.0007976091978914681

    class1:
        color:
            R:  0
            G:  102
            B:  0
        weight: 0.2913455129929105

    class2:
        color:
            R:  0
            G:  102
            B:  102
        weight: 0.005224675677940002

    class3:
        color:
            R:  0
            G:  153
            B:  153
        weight: 0.018517698236153693

    class4:
        color:
            R:  0
            G:  255
            B:  0
        weight: 0.14592118584029914

    class5:
        color:
            R:  0
            G:  255
            B:  255
        weight: 0.01313123697869497

    class6:
        color:
            R:  102
            G:  0
            B:  0
        weight: 0.09552945122836413

    class7:
        color:
            R:  102
            G:  0
            B:  102
        weight: 0.04887260934092041

    class8:
        color:
            R:  102
            G:  102
            B:  0
        weight: 0.00172073445612366

    class9:
        color:
            R:  153
            G:  0
            B:  153
        weight: 0.19027731073074847

    class10:
        color:
            R:  153
            G:  153
            B:  0
        weight: 0.006524524841233285

    class11:
        color:
            R:  255
            G:  0
            B:  0
        weight: 0.06603666735259975

    class12:
        color:
            R:  255
            G:  0
            B:  255
        weight: 0.11209021851644496

    class13:
        color:
            R:  255
            G:  255
            B:  0
        weight: 0.004010564609675552

