_target_: src.datamodules.RolfFormat.datamodule.DataModuleRolfFormat

num_workers: 4
batch_size: 16
shuffle: True
drop_last: True

data_root: /netscratch/datasets/semantic_segmentation/rolf_format

train_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1000
        range_to:   1059
    append2:
        doc_dir:    "SetA1_sizeM_Rolf/layoutR/data"
        doc_names:  "A1-MR-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutR/gtruth"
        gt_names:   "A1-MR-truthD-####.gif"
        range_from: 1000
        range_to:   1059

val_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1060
        range_to:   1079
    append2:
        doc_dir:    "SetA1_sizeM_Rolf/layoutR/data"
        doc_names:  "A1-MR-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutR/gtruth"
        gt_names:   "A1-MR-truthD-####.gif"
        range_from: 1060
        range_to:   1079

test_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1080
        range_to:   1099
    append2:
        doc_dir:    "SetA1_sizeM_Rolf/layoutR/data"
        doc_names:  "A1-MR-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutR/gtruth"
        gt_names:   "A1-MR-truthD-####.gif"
        range_from: 1080
        range_to:   1099

image_dims:
    width:  640
    height: 896

image_analytics:
    mean:
        R: 0.8664800196201524
        G: 0.7408864118075618
        B: 0.6299955083595935
    std:
        R: 0.2156624188591712
        G: 0.20890185198454636
        B: 0.1870731300038113

classes:
    class0:
        color:
            R: 0
            G: 0
            B: 0
        weight: 0.0016602289391364547
    class1:
        color:
            R: 0
            G: 102
            B: 0
        weight: 0.22360020547468618
    class2:
        color:
            R: 0
            G: 102
            B: 102
        weight: 0.014794833923108578
    class3:
        color:
            R: 0
            G: 153
            B: 153
        weight: 0.05384506923533185
    class4:
        color:
            R: 0
            G: 255
            B: 0
        weight: 0.1115978481679602
    class5:
        color:
            R: 0
            G: 255
            B: 255
        weight: 0.037436533973406926
    class6:
        color:
            R: 102
            G: 0
            B: 0
        weight: 0.12569866772812885
    class7:
        color:
            R: 102
            G: 0
            B: 102
        weight: 0.03591164457353043
    class8:
        color:
            R: 102
            G: 102
            B: 0
        weight: 0.01062086078798502
    class9:
        color:
            R: 153
            G: 0
            B: 153
        weight: 0.1491578366712268
    class10:
        color:
            R: 153
            G: 153
            B: 0
        weight: 0.0414074692141804
    class11:
        color:
            R: 255
            G: 0
            B: 0
        weight: 0.08600602291055298
    class12:
        color:
            R: 255
            G: 0
            B: 255
        weight: 0.08349157426652898
    class13:
        color:
            R: 255
            G: 255
            B: 0
        weight: 0.024771204134236315


