_target_: src.datamodules.RolfFormat.datamodule.DataModuleRolfFormat

num_workers: 4
batch_size: 8
shuffle: True
drop_last: False

data_root: /netscratch/datasets/semantic_segmentation/rolf_format

train_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1000
        range_to:   1059

val_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1060
        range_to:   1079

test_specs:
    append1:
        doc_dir:    "SetA1_sizeM_Rolf/layoutD/data"
        doc_names:  "A1-MD-page-####.jpg"
        gt_dir:     "SetA1_sizeM_Rolf/layoutD/gtruth"
        gt_names:   "A1-MD-truthD-####.gif"
        range_from: 1080
        range_to:   1099

image_dims:
    width:  640
    height: 896

image_analytics:
    mean:
        R: 0.8616756883580258
        G: 0.7419672402489641
        B: 0.6295439441727211
    std:
        R: 0.21909338297170539
        G: 0.2076260211193138
        B: 0.1875025535444422

classes:
    class0:
        color:
            R: 0
            G: 0
            B: 0
        weight: 0.00047694816117914033
    class1:
        color:
            R: 0
            G: 102
            B: 0
        weight: 0.2750549630858548
    class2:
        color:
            R: 0
            G: 102
            B: 102
        weight: 0.0032424343955529127
    class3:
        color:
            R: 0
            G: 153
            B: 153
        weight: 0.011400733756796401
    class4:
        color:
            R: 0
            G: 255
            B: 0
        weight: 0.13777394656361366
    class5:
        color:
            R: 0
            G: 255
            B: 255
        weight: 0.008088433280055035
    class6:
        color:
            R: 102
            G: 0
            B: 0
        weight: 0.09080998823458127
    class7:
        color:
            R: 102
            G: 0
            B: 102
        weight: 0.05538750877701472
    class8:
        color:
            R: 102
            G: 102
            B: 0
        weight: 0.0019513173654070824
    class9:
        color:
            R: 153
            G: 0
            B: 153
        weight: 0.21392691331701744
    class10:
        color:
            R: 153
            G: 153
            B: 0
        weight: 0.007439598839196634
    class11:
        color:
            R: 255
            G: 0
            B: 0
        weight: 0.06261423912267086
    class12:
        color:
            R: 255
            G: 0
            B: 255
        weight: 0.12729126435641605
    class13:
        color:
            R: 255
            G: 255
            B: 0
        weight: 0.004541710744643828
