f1_score:
    # more infos about parameters: https://torchmetrics.readthedocs.io/en/latest/references/modules.html#f1
    _target_: torchmetrics.F1Score

    average: none
    mdmc_reduce: global
    num_classes: ${datamodule:num_classes}