jaccard_index:
    # more infos about parameters: https://torchmetrics.readthedocs.io/en/latest/references/modules.html#iou
    _target_: torchmetrics.classification.MulticlassJaccardIndex

    num_classes: ${datamodule:num_classes}
    average: none