precision:
    # more infos about parameters: https://torchmetrics.readthedocs.io/en/latest/references/modules.html#id4
    _target_: torchmetrics.classification.MulticlassPrecision

    average: none
    mdmc_reduce: global
    num_classes: ${datamodule:num_classes}