recall:
    # more infos about parameters: https://torchmetrics.readthedocs.io/en/latest/references/modules.html#id5
    _target_: torchmetrics.Recall

    average: macro
    mdmc_reduce: global
    num_classes: ${datamodule:num_classes}