name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Set Python Path
      run: |
        echo "PYTHONPATH=$PYTHONPATH:." >> $GITHUB_ENV

    - name: Install pip dependencies
      run: | 
        pip install --requirement requirements.txt --upgrade --quiet --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install --requirement tests/requirements.txt --quiet

    - name: Tests
      run: |
        coverage run -m pytest -v

    - name: Statistics
      if: success()
      run: |
        coverage report -m

    - name: Produce statistics xml
      if: success()
      run: |
        coverage xml

    - name: SonarCloud Scan
      if: success()
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
